### ISSUE TITLE
Hasher fails to find 'argon2id' implementation

### ISSUE THREAD

**Issue by vkz** [Bogdanp/koyo#18]
Hi Bogdan.

Getting this atm with current master. I wonder if your libargon2 package actually installs the libargon2.dylib. Not quite sure how to check.

```
16:56:39 web.1    | [2020-05-07 16:56:39] [   96161] [  error] hasher: unhandled error: pwhash: could not get implementation
16:56:39 web.1    |   KDF: 'argon2id
```

Above comes from the Racket `crypto` lib but is being reported by your logger. Steps to reproduce:
- fresh install `koyo` I did `raco pkg intsall -u --clone koyo` so its linked and is using current master,
- go through install steps as described in the generated README.md,
- try to register a user via the signup page

**Comment by Bogdanp** [comment]
Hey! That's really odd. What does `~/Library/Racket/7.6/lib/` look like for you? You'll have to 7.6 for whatever version of Racket you're using, but I'm surprised it's not finding it because I use that library myself. If you remove and then reinstall it, you should be able to see if it places anything in your `lib` directory because there should be a couple lines like

```
raco setup: --- installing foreign libraries ---                   [22:24:39]
raco setup: installing: foreign library <lib>/libargon2.dylib
```

or just

```
raco setup: --- installing foreign libraries ---                   [22:24:39]
raco setup: --- something else ...
```

if, for whatever reason, the platform specifier doesn't match your machine.

Other things to try:

* check if the libargon2 package is installed at all with `raco pkg show -l libargon2-x86_64-macosx`
* check if `(matching-platform? #rx"x86_64-macosx")` returns `#t`

**Comment by vkz** [comment]
all of the above are true. Have the shared lib installed. Reinstalled just in case and it does end up in ~/Library/racket ... as it should. Starting to think maybe the recent crypto is borked or the upstream libargon2 broke something like argon2id symbol isn't there or something

**Comment by vkz** [comment]
argh, I am on the recent Racket CS built from source and it maybe the one before FFI was reinstated, so that may well be the problem. I guess I'll have to pull recent changes and rebuild Racket to see if it works. May also try Racket vanilla

**Comment by Bogdanp** [comment]
I've updated the libargon2 README to include a compatibility table and I think that plus the additional logging that Ryan added should make this less confusing in the future so I'm going to close this issue. Thanks for digging into it!
