### ISSUE TITLE
Using with sqlite?

### ISSUE THREAD

**Issue by vendethiel** [Bogdanp/koyo#53]
Hi! I tried to use koyo with sqlite, but it gave me an error saying that I needed to provide a DB port. However, that doesn't make much sense with sqlite.

The [database module documentation](https://docs.racket-lang.org/koyo/database.html) seems to indicate that it should be possible, so I'm guessing I missed something?

**Comment by Bogdanp** [comment]
I'm afraid it's a bit of a pain to use SQLite if you're starting from the standard blueprint, sorry! 

You should be able to connect to a SQLite database by setting an `<APP_NAME_HERE>_DATABASE_URL` (see [this doc](https://docs.racket-lang.org/koyo/database.html#%28def._%28%28lib._koyo%2Fdatabase-url..rkt%29._parse-database-url%29%29)) in your `.env` file, and changing the `define-option` for `db-port` to have a `#:default` of `(and default-db-port (number->string default-db-port))` instead of just `(number->string default-db-port)`. You'll also have to update the two migrations in your migrations folder to fit the SQLite syntax.

**Comment by Bogdanp** [comment]
> Sorry, forgot to close this. Thanks for your answer.

No worries!
