### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by srfoster** [Bogdanp/koyo#6]
Is there an example app somewhere that uses Koyo?  The docs are looking thorough, but I'd love to poke around in some source code.

**Comment by Bogdanp** [comment]
[nemea](https://github.com/bogdanp/nemea) uses koyo, though not to the full extent since nemea predates this library. nemea itself is also a little rough since it was my first project using Racket. koyo is also heavily used by my e-commerce site, [matchacha.ro](https://www.matchacha.ro/) (in fact, everything in koyo is something I extracted from that codebase) but that's not open source. If you run `raco koyo new`, then you should end up with a working web application with basic support for user registration and authentication (though not  much else). I think that's the extent of what's available publicly.

**Comment by Bogdanp** [comment]
@srfoster a year late, but maybe this might help: https://www.youtube.com/watch?v=DS_0-lqiSVs
